<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="CoEConfig" Id="{ac67faf6-46b9-4ce7-a6dd-13d16b67c657}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM CoEConfig
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="CoEConfig">
      <LineId Id="3" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>