<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.9">
  <POU Name="FB_GetExtPosition" Id="{f5e01ce2-6344-4d08-82f0-00634db46d42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_GetExtPosition
VAR_INPUT
	tableIdx		: DINT;
	tableOffset	: LREAL;
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[;]]></ST>
    </Implementation>
    <LineIds Name="FB_GetExtPosition">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>